### ISSUE TITLE
Provide an energy return sensor (solar panels)

### ISSUE THREAD

**Issue by ldotlopez** [ldotlopez/ha-ideenergy#10]
Basically title.

I don't have access to any contract with energy return, so I need some information from people with any kind of energy  generation installation.

Please send me logs with information.

* Option A: from homeassistant:

Activate debug from ideenegy, in `configuration.yaml` insert this:
```
logger:
  logs:
    ideenergy: debug
    custom_components.ideenergy: debug
```

Send me lines with this type of info:
```
ha-core | 2022-05-11 03:52:35 DEBUG (MainThread) [custom_components.ideenergy.api] Got reply, raw data: {'valMagnitud': '80.0', 'valInterruptor': '1', 'valEstado': '09', 'valLecturaContador': '45882', 'codSolicitudTGT': '011445362000'}
```

* Option B: using ideenergy command line

1. Download and install ideenergy pyth on module (`pip install ideenergy` or whatever suits you)
2. Send me the output of running `python -m ideenergy --username xxxxx --password xxxxx  --get-measure  --retries 3`

**Comment by ldotlopez** [comment]
Antes de poder exponer esta información es necesario el soporte en `ideenergy`:
https://github.com/ldotlopez/ideenergy/issues/3

**Comment by davefx** [comment]
Hola ¿Cual es el estado de esta mejora?

**Comment by ad-ha** [comment]
> Hola ¿Cual es el estado de esta mejora?

Creo que eso ya está implementado en la última versión 1.0. Los sensores están desactivados al instalar, los tienes que activar manualmente.

Todavía no tengo placas instaladas para comprobar, pero de lo que entendí de @ldotlopez, eso ya está implementado.

**Comment by ldotlopez** [comment]
@davefx 

Está implementado en la última versión pero hay que habilitarlo manualmente ("Historical generation").

Sin embargo, debido a que no se generan estadísticas (#25) la utilidad puede ser limitada. Yo tampoco dispongo de paneles así que tampoco puedo decir hasta que punto.

![imagen](https://user-images.githubusercontent.com/99769/210262491-b1d59e7a-bc26-402b-b84e-3e7b24bdb7ba.png)
