### ISSUE TITLE
Improve README 

### ISSUE THREAD

**Issue by ad-ha** [ldotlopez/ha-ideenergy#12]
Improve README documentation, with further details on installation and HACS support.

**Comment by ldotlopez** [comment]
@ad-ha  I think README from integration is pretty good, we can use it as base README and pick some stuff from current README.

**Comment by ad-ha** [comment]
@ldotlopez Perdona pero no entendi.

**Comment by ldotlopez** [comment]
Más allá de que mi comentario contenía errores y me había comido palabras… tal vez deberíamos establecer una convenio sobre el idioma a usar en el proyecto, no me defiendo mal pero tampoco es muy fuerte… 😪 Al ser un proyecto tan local y con el público objetivo que puede tener tal vez sea conveniente usar el castellano en la documentación. Tal vez en otra issue se puede abordar
 
En cualquier caso, @ad-ha, comentaba que el [README de tu integración](https://github.com/ad-ha/ide_api/blob/main/README.md) me parece muy bueno. Sugería usarlo como base y añadir las cuatro cosas que consideremos relevantes del actual README.

**Comment by ad-ha** [comment]
De acuerdo. Entendido. Era lo que creía, pero no estaba seguro si te referias a mi README. En cuanto tenga un momento lo preparo y subo el PR.

Respecto al idioma, estoy de acuerdo con el castellano. Yo normalmente es que me da por hacerlo en inglés, al menos el título y el primer post. Pero mejor pasar todo a castellano y con enfoque más local :)

**Comment by ad-ha** [comment]
Cerrado con el PR #17
