### ISSUE TITLE
Add I-DE logo to HA Brands

### ISSUE THREAD

**Issue by ad-ha** [ldotlopez/ha-ideenergy#13]
The Integration currently does not show a logo on the "Integrations" page of Home Assistant.

Propose to add i-DE logo to the https://github.com/home-assistant/brands within the `ideenergy` domain

**Comment by ldotlopez** [comment]
Perfecto aunque no tengo claro si podemos fusilar el logo tal cual, por derechos de imagen. Tal vez habría que hacer uno parecido.
Me pilla un poco fuera de juego esto

**Comment by ad-ha** [comment]
> podemos fusilar el logo tal cual

Creo que sí, es una imagen y se puede usar. No es que nos estemos apropiando de nada. En HA se usan logos de todas las marcas y, que yo sepa, no ha habido cualquier problema con ello.

**Comment by ldotlopez** [comment]
Hola,

Hace unos días estuve mirando el tema y preparé icono y logo para hacer el PR a homeassistant-brands:
https://github.com/ldotlopez/ha-ideenergy/tree/main/assets

Hay unas directrices:
https://github.com/home-assistant/brands/blob/master/README.md

Pero me quedé ahí, lo comento para evitar el trabajo de preparar las imágines.

**Comment by ad-ha** [comment]
Hola,

Ya he conseguido un momento e hice un PR en Brands: https://github.com/home-assistant/brands/pull/3439

Añadí las dos versiones de icono y logo. @ldotlopez he dejado más espacio que lo que tenías, porque los iconos se muestran circulares y luego habría partes del logo que no se verían.

A ver si lo aprueban

**Comment by ldotlopez** [comment]
Gracias @ad-ha, no había tenido en cuenta la posibilidad de que aparecieran circulares, me había ceñido a eliminar los bordes. 👍 

De momento parece que ha pasado los checks y creo que está a la espera de la aprobación manual 🤞

**Comment by ad-ha** [comment]
El PR de Brands ha sido aprobado e incorporado a Main. En unos días debería empezar a salir el logo en HA.
