### ISSUE TITLE
Instalación 

### ISSUE THREAD

**Issue by gaRFio01** [ldotlopez/ha-ideenergy#14]
Hola:
He instalado el componente en Homeassistant a través de HACS.
Sin embargo, al reiniciar no sé cómo tengo que continuar para enlazar con i-DE. Como saco el wizard para conectar?
Tampoco me parece ningún sensor nuevo…
He probado a reinstalar y reiniciar de nuevo…

**Comment by ad-ha** [comment]
Hola,

En HA 2022.05 tienes que ir a Settings >> Devices & Services y luego pulsar en `ADD INTEGRATION`. Ahí buscas por i-DE y pones tu usuario y contraseña de I-DE. Y es solo esperar a que te aparezca la lista de contratos y seguir los pasos. 

Espero que ayude.

**Comment by ad-ha** [comment]
En breve actualizaré el README con estas instrucciones.

**Comment by gaRFio01** [comment]
Si. Me ha ayudado mucho. Ya tengo la integración funcionando. Muchas gracias!!
