### ISSUE TITLE
Mismo valor en dos contratos diferentes

### ISSUE THREAD

**Issue by liebefuroscar** [ldotlopez/ha-ideenergy#16]
Buenos días!
Tengo dos contratos con Iberdrola y en los dos me muestra el mismo valor.
He probado teniendo sólo el sensor 1, teniendo sólo el sensor 2 y teniendo simultáneamente sensor 1 y 2.
![Captura de pantalla 2022-05-19 123109](https://user-images.githubusercontent.com/25435711/169273544-e08cd660-3a60-4bda-838d-886a6167c302.jpg)

**Comment by ldotlopez** [comment]
Hola, 

¿Tienes acceso a linea de comandos dentro de homeassistant?

**Comment by ldotlopez** [comment]
Otra pregunta, cuando tenías configurados por separado e individualmente uno y otro sensor ¿siempre te saca el mismo valor? Es decir, hay una vivienda de la que nunca has recibido el valor correcto, ¿no?

**Comment by liebefuroscar** [comment]
Creo que sí, tellme

**Comment by liebefuroscar** [comment]
> Otra pregunta, cuando tenías configurados por separado e individualmente uno y otro sensor ¿siempre te saca el mismo valor? Es decir, hay una vivienda de la que nunca has recibido el valor correcto, ¿no?

Sí. el mismo valor, correspondiente al contrato "principal"

**Comment by ldotlopez** [comment]
En realidad voy a ir aprovechando para hacer unas instrucciones de diagnostico.

1. Crear entorno aislado:
```
python3 -m venv /tmp/ide-test
/tmp/ide-test/bin/pip install ideenergy==0.0.7
```
2. Listar contratos:
```
/tmp/ide-test/bin/python -m ideenergy --list-contracts -u  xxxxxxxxxxx -p xxxxxxxxxxx
``` 

Deberias obtener algo similar a esto:
```
{'12345': {'codContrato': '12345',
               'cups': 'ESXXXXXXXXXXXXXXXXXXXXXXx',
... 
}}
```

3. Para cada contrato  (12345 o el valor de codContrato) ejecuta:
```
/tmp/ide-test/bin/python -m ideenergy --contract 12345  --get-measure  -u xxxxxxxxxxx -p xxxxxxxxxxx
```
Deberías obtener valores diferentes (cuando el contador responda correctamente, que no es siempre)

**Comment by liebefuroscar** [comment]
Hola! Haciéndolo así sí que me da un valor diferente al que he mostrado en la primera imagen.
He probado sólo con el valo
![WIN](https://user-images.githubusercontent.com/25435711/169278736-196ef4b1-6de7-43aa-9911-f78ee355abc2.jpg)
r de contrato "no principal" y el resultado ha sido satisfactorio.
2124 vs 8412 que marcaba anteriormente.

**Comment by ldotlopez** [comment]
Ok, gracias. Podemos descartar que el fallo esté en el modulo que implementa el acceso al API, el problema está en la integración.

Tendré que revisarlo con calma, unos días. Estoy pendiente.

**Comment by liebefuroscar** [comment]
Por añadir algo más, que puede que te ayude a depurar, me he dado cuenta que cuando realizo "/tmp/ide-test/bin/python -m ideenergy --contract 12345  --get-measure  -u xxxxxxxxxxx -p xxxxxxxxxxx" poniendo los datos del contrato 1 me salen los datos como tienen que ser, pero en HA me salen algo cambiados.

En HA me aparece "ID de la entidad": sensor.icp_CUPS_de_contrato_1 pero aparecen los kWh de contrato 2. 
Y a la inversa, en "ID de la entidad": sensor.icp_CUPS_de_contrato_2 aparecen los kWh de contrato 1.

Esto es curioso porque antes me aparecían los dos valores iguales (8412 kWh)
Y después se me igualaron los dos a 2124 kWh.
Es posible que los dos sensores estén marcando el valor que se obtiene cuando realizo "/tmp/ide-test/bin/python -m ideenergy --contract 12345  --get-measure  -u xxxxxxxxxxx -p xxxxxxxxxxx" aunque sea de otro contrato?
Tendremos que llamar a Iker Jiménez? :D

**Comment by ldotlopez** [comment]
Hola @liebefuroscar,

He publicado una versión beta de la integración.
Para descargarla tienes que ir a HACS → i-de → ... → Volver a descargar → Activar versiones beta → v0.2.2a1

Antes de reiniciar añade estos valores a tu configuration.yaml para poder sacar el debug en caso de que no funcione como toca:
```
logger:
  default: warning
  logs:
    ideenergy: debug
    custom_components.ideenergy: debug
```

A ver si hay suerte.

**Comment by liebefuroscar** [comment]
Buenos días!
De momento no lo puedo comprobar.
Tenía la integración en dos HA diferentes y han bloqueado el usuario de IDE.
Acabo de mandar un mail pidiendo la reactivación.

**Comment by liebefuroscar** [comment]
Hola!
De 3 contratos, me está marcando dos, con valores diferentes.
![image](https://user-images.githubusercontent.com/25435711/173520457-85387933-b596-4ece-b7da-999a0335153c.png)

Pero de los dos que marca, a veces intercambian el valor y es un jaleo.
![image](https://user-images.githubusercontent.com/25435711/173520426-340a6788-0057-42fa-b704-c2b9bdbaef87.png)
![image](https://user-images.githubusercontent.com/25435711/173520508-b4e2a174-91cc-4573-802a-860867b3a2a5.png)

**Comment by liebefuroscar** [comment]
Sí, estoy usando esa versión.
![image](https://user-images.githubusercontent.com/25435711/173532275-0f34effe-ca59-49f2-9c7d-f7c5c45ddaa1.png)

Por lo visto hacer 3 peticiones a la hora (3 contratos) no le gusta a IDE...

**Comment by ldotlopez** [comment]
Hola @liebefuroscar 

En la issue #36 han aparecido algunos datos que es posible que hayan solucionado este error.
