### ISSUE TITLE
User is not logged or session is too old

### ISSUE THREAD

**Issue by ad-ha** [ldotlopez/ha-ideenergy#19]
Buenas,

Desde ayer, incluso después de reiniciar HA, me ha empezado a salir este mensaje de error:

![image](https://user-images.githubusercontent.com/59612788/173521019-afcea2b8-7349-4cea-a638-e98a6a8b126f.png)

Que me imagino que vendrá relacionado con esto:

![image](https://user-images.githubusercontent.com/59612788/173521691-0ae2a5c5-534b-4395-8611-efd52959ebc2.png)

Un saludo

**Comment by ldotlopez** [comment]
Buenas,

Tenemos varias cosas:

- El primer "error" (User is not logged or session is too old) es normal, es un warning. Lo añadí al API (módulo ideenergy) para poder hacer un mejor debug sobre el tema de múltiples contratos. Cuando se realiza una lectura cada hora es lógico que la sesión haya caducado. De todos modos lo rebajaré a debug y lo haré menos "intimidante".

- Sobre "valLecturaContador": voy a revisar como gestiona ideenergy las respuestas del contador, parece que no está capturando bien las respuestas vacías (a veces el contador devuelve un '{}', sin más). Este error debería ser temporal aunque hay que manejarlo correctamente.

 - El tercer error, "TypeError: event is an invalid keyword argument for States" ya es más peliagudo. Proviene del sensor historico (desactivandolo desaparecería el error) y se debe a que genera entradas en la base datos sin pasar por el core de homeassistant. Seguramente se haya actualizado algo en el core y haya que modificar como se generan los estados.
 
 A ver que día tengo un rato y me pongo.

**Comment by ad-ha** [comment]
Parece que hay un problema con i-DE. Acabo de intentar ver el consumo en la web, directamente, y sale un mensaje de error y que no es posible acceder al sistema. Será por eso que falla la lectura.

A ver si lo solucionan.

Un saludo

**Comment by ldotlopez** [comment]
He publicado nuevas versiones del API y de la integración que deberían solucionar los dos bugs.
Es necesario homeassistant 2022.06.06 (la versión actual)

**Comment by francisco-navarro** [comment]
Con la última versión de vez en cuando tengo que reiniciar la integración:


2022-07-30 22:46:10 WARNING (MainThread) [custom_components.ideenergy.api] User is not logged or session is too old

Reinicio la integración y vuelve a funcionar, el problema que tengo que estar todos los días pendiente.

**Comment by ldotlopez** [comment]
@francisco-navarro No se trata de un error, es simplemente un warning. A menos que haya mensajes de error la integracióin se encarga de volver a identificarse ante i-de.

Otro tema es que el "API" (no es oficial) de i-de es muy problemático y haya periodos en los que no se consiga leer el contador. No hay otro modo de funcionar.

En resumen, si no tienes errores no es necesario que reinicies cada día, simplemente deja hacer a la integración
