### ISSUE TITLE
Estado desarrollo

### ISSUE THREAD

**Issue by vfs-code** [ldotlopez/ha-ideenergy#2]
Hola Luis, que tal va el desarrollo de esta integracion? Estaba mirando para hacer la mia pero veo que tu ya te pusiste manos a la obra, te agradeceria si pudieras completar el README con la info sobre como usar la integracion, como y donde añadir nuestros datos user/pass, MQTT, y otras cosas que consideres necesarias

**Comment by ldotlopez** [comment]
Hola,

Tenía pendiente unos cambios en la integración que subí ayer.

La integración ahora funciona desde el interfaz, solo tienes que ponerla en
el directorio `config/custom_integrations` y activarla desde el interfaz
web como `i-de.es consumption energy sensor`
