### ISSUE TITLE
Integración en Energy panel

### ISSUE THREAD

**Issue by ralunagithub** [ldotlopez/ha-ideenergy#20]
Hola. Podriais indicar como integrarlo en el energy panel? 
En "Configuration/Energy/Electricity Grid/Add consumption" aparece "icp_es_xxxx", pero no me deja escogerlo. Gracias
![Energy](https://user-images.githubusercontent.com/64015936/174456285-e5e145a5-4a0e-470a-aa4d-747eeeb9394d.jpg)

**Comment by ldotlopez** [comment]
Hola,

Si te aparece en la lista deberías poder escogerlo, ¿tal vez se trata de un fallo en el frontend?
