### ISSUE TITLE
Obtener valor de potencia

### ISSUE THREAD

**Issue by josecarre** [ldotlopez/ha-ideenergy#24]
Hola, ahora mismo esta integración de i-de para HA solo obtiene el valor del contador para integrarlo con el panel de energía de HA, muchas veces las peticiones a i-de fallan por lo que el contador en la grafica de HA tiene "saltos", imagino que por peticiones que no dan respuesta... una pena, pero mi propoesta es la de añadir otros valores como la potencia consumida en el momento.

Según he visto en las peticiones de la app, se hacen a `https://www.i-de.es/consumidores/rest/escenarioNew/obtenerMedicionOnline/24` con los headers de cookie...etc

Y se obtiene una respuesta de este tipo:
```
{
  "valMagnitud": "240.0",
  "valInterruptor": "1",
  "valEstado": "09",
  "valLecturaContador": "17147",
  "codSolicitudTGT": "0125*******900"
}
```

Sería posible almacenar el valor de `valMagnitud` en un sensor de tal manera que podamos ver que consumo instantaneo hay en la vivienda?
No se que límites permite la API de i-de... parece fallar mas que una escopeta de feria, pero sería ideal obtener este valor una vez por minuto por ejemplo.

Gracias!

**Comment by ldotlopez** [comment]
Hola Josechu,

He estado estas semanas en la rama main de la integración para poder hacer
lo que comentas.

Tengo casi listos los cambios para publicar una versión y aunque no añadirá
esos sensores implementarlos será trivial.

El problema es, como comentas, el API de i-de. Es muy sensible y falla
muchisimo, hay usuarios que han tenido problemas (les bloquean la cuenta)
simplemente por hacer 3 peticiones en un breve intervalo (~5 minutos). Esta
integración solo consulta el API una vez cada hora para obtener datos en
tiempo real (los que comentas).

Mi idea es implementar una entidad "botón" de modo que se puedan refrescar
esos datos de forma manual cuando los necesites y actualizar los sensores
correspondientes. Pero como te comento eso será una vez publique la versión
con los cambios de arquitectura.

Saludos.

**Comment by josecarre** [comment]
Suena muy bien Luis, muchas gracias :)

Para tener el consumo instantaneo en HA creo que me va a tocar comprar "algun chisme físico", la API no parece muy amigable de las consultas recurrentes como dices :(

**Comment by ad-ha** [comment]
Buenas,

Perdonadme que ando ocupado y no he podido contestar antes. 

@josecarre la integración ya tiene el consumo instantáneo funcionando, aunque aparece como un atributo, no como un sensor. Al acceder al sensor, si pulsas en Atributos, te saldrá el último consumo instantáneo: 

![image](https://user-images.githubusercontent.com/59612788/191944415-87caf24d-b9dd-4845-856c-9a5f9fc23ce4.png)

**Comment by josecarre** [comment]
Muchas gracias por la respuesta, lo veo ahora si, estaba escondido :). Sería posible habilitar la opción de elegir el tenerlo como un sensor aparte y el número de queries por hora? Me gustaría obtener el valor cada minuto, y tener así tener una gráfica un poco acorde con el consumo
Thanks

**Comment by ad-ha** [comment]
> Sería posible habilitar la opción de elegir el tenerlo como un sensor aparte?

Creo que eso es lo que está preparando @ldotlopez 

> Me gustaría obtener el valor cada minuto

Con las limitaciones de consultas al contador, por la API de I-DE, eso lo veo imposible. Para conseguir esa información lo mejor será que instales directamente un monitor de consumo en el cuadro general. Con I-DE eso no va a ser posible (a no ser que algún día cambien la API)
