### ISSUE TITLE
Falta configuración de los valores nuevos entregados

### ISSUE THREAD

**Issue by JaVier-Lloret** [ldotlopez/ha-ideenergy#26]
Tras los ultimos cambios los valores entregados "sensor.ideenergy_esXXXXXXXXXX_accumulated_consumption" y demas, no tienen el campo que los acredita como valor seleccionable para estadísticas. (total_increasing o measurement) y no son incluidos en el desplegable de selección de la tarjeta de energía.

De momento lo he apañado creando un nuevo valor con el nombre antiguo y vinculado al nuevo.

template:
- sensor:
    - name: "icp_esXXXXXX_accumulated"
      unit_of_measurement: "kWh"
      state_class: total_increasing # measurement
      device_class: energy
      state: "{{ (states ('sensor.ideenergy_esXXXXXXX_accumulated_consumption')) }}"

Ya nos contaras.

Por cierto como perdí los valores he hice varias pruebas los de IDE me bloquearon el usuario, que ticquismiquis se han vuelto.

**Comment by JaVier-Lloret** [comment]
Se me olvido vincular el problema, tal como se aconseja en HA, a  https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics .

**Comment by ldotlopez** [comment]
Hola Javier,

Actualmente (en la rama v1.0.0) el sensor se reporta como TOTAL y funciona correctamente con las estadísticas.
https://github.com/ldotlopez/ha-ideenergy/blob/releases/v1.0.0/custom_components/ideenergy/sensor.py#L85

Espero sacar una pre-release en los próximos días.

Saludos.

**Comment by JaVier-Lloret** [comment]
Gracias por tu respuesta.Porcierto con la versión 0.2.3 me han bloqueado dos veces. ¿Es esta la versión que comentaste que tenia un problema y hacía exceso de preguntas al servidor ide?Un saludoJaVier Lloret Enviado desde mi Galaxy
-------- Mensaje original --------De: Luis López ***@***.***> Fecha: 20/11/22  14:55  (GMT+01:00) Para: ldotlopez/ha-ideenergy ***@***.***> Cc: JaVier-Lloret ***@***.***>, Author ***@***.***> Asunto: Re: [ldotlopez/ha-ideenergy] Falta configuración de los valores nuevos entregados (Issue #26) 

Hola Javier,

Actualmente (en la rama v1.0.0) el sensor se reporta como TOTAL y funciona correctamente con las estadísticas.

https://github.com/ldotlopez/ha-ideenergy/blob/releases/v1.0.0/custom_components/ideenergy/sensor.py#L85

Espero sacar una pre-release en los próximos días.

Saludos.

**Comment by ldotlopez** [comment]
Ahora mismo en mi instalación de casa estoy usando el mismo código que hay en la rama v1.0.0 y no me han bloqueado. 
También es cierto que llevo un par de días sin conseguir una lectura correcta y me mosquea. Lo cierto es que parece ser que i-de ha hecho tareas de mantenimiento en sus sistemas y puede haber cambiado algo.
