### ISSUE TITLE
No puedo agregar el repositorio con la url

### ISSUE THREAD

**Issue by jaldales** [ldotlopez/ha-ideenergy#28]
Buenas;

En primer lugar agradecer el trabajo realizado en este proyecto. Espero poder probarlo pronto porque tiene muy buena pinta.

El tema es que he tratado de agregar el repositorio en complementos de mi HA pero dice que no es un addon correcto.

https://github.com/ldotlopez/ideenergy is not a valid add-on repository

He buscado en otras opciones de los menús pero el único sitio donde puedo agregar repositorios es en complementos pero no me deja.

¿sabrías darme alguna pista para ver que estoy haciendo mal o debo ir a la opción de copia manual?

Gracias

**Comment by ad-ha** [comment]
Hola, @jaldales 

El repositorio que tienes que usar en HA es este: https://github.com/ldotlopez/ha-ideenergy

Un saludo

**Comment by jaldales** [comment]
Buenas;

Estoy intentando agregarlo en repositorio de complementos y me dice de nuevo:

https://github.com/ldotlopez/ha-ideenergy is not a valid add-on repository

Hay otro sitio para incorporar repositorios de integraciones??

Un saludo

**Comment by ldotlopez** [comment]
Entiendo que está solucionado.

De todos modos dejo aquí las instrucciones de instalación:
https://github.com/ldotlopez/ha-ideenergy#installation
