### ISSUE TITLE
Still interruptions with every update of HA and losing data

### ISSUE THREAD

**Issue by hartmood** [ldotlopez/ha-ideenergy#31]
Hi,
There was an update of HA core today and after the restart ide-energy does not work anymore. Isn’t there a way to have a smooth update policy as this happens with every update of HA? Plus I lost all my data from last year with the update to 1.0.1 from 1.0.rc2. 

Any ideas what might me wrong in my HACS installation and how to fix this?

**Comment by ldotlopez** [comment]
Hi,

I'm sorry to hear that you're experiencing problems with the integration.

I run this integration in my own setup, both H-A and ideenergy at the
latest stable versions (ideenergy: 1.0.1, HomeAssistant: 2023.1.2) and I
haven't encountered any issues, including interruptions or data loss.

If you have any logs or information that might help identify the problem,
I'd be happy to take a look and see if I can help.

**Comment by hartmood** [comment]
thanks for your support. This was the error message I received. Then I re-downloaded 1.0.1 and after a restart the error message disappeared and it worked fine. 

```
Logger: homeassistant.setup
Source: setup.py:202 
First occurred: 14:16:19 (1 occurrences) 
Last logged: 14:16:19

Setup failed for custom integration ideenergy: Requirements for ideenergy not found: ['ideenergy==1.0.1'].
```
