### ISSUE TITLE
Sensor en tiempo real

### ISSUE THREAD

**Issue by pgalinanes** [ldotlopez/ha-ideenergy#39]
Hola buenas, primero que nada agradecer tu trabajo. Leyendo el readme, veo que indicas que hay un sensor en tiempo real de consumo, y viendo el archivo sensors.yaml, veo que también está, pero al añadir la integración no me aparece. Es un problema conocido o es algo mío particular?

**Comment by ad-ha** [comment]
Hola,

Entiendo, no obstante, que los demás sensores de lectura sí te aparecen, no?

De ser así, el sensor en tiempo real es el de lectura del contador y de la potencia instantánea en el momento de la lectura. No hay un sensor con actualización minuto a minuto, es simplemente lectura horaria, siempre y cuando se pueda conectar con el contador (que no siempre funciona) y cuando el consumo respecto a la última lectura sea superior a 1. 

Es decir, si en una hora consumes solamente 0.8 kWh, ese consumo no se registra (basicamente la API sólo reporta números enteros) hasta que la diferencia entre lecturas no sea superior a 1 kWh.

Espero haber ayudado

**Comment by pgalinanes** [comment]
Entiendo,  he probado el pull request que hay de un sensor de "consumo instantaneo", que llama a la api 1 vez por hora y funciona el 90% de las veces, el resto entiendo que es un fallo de I-de. Hay alguna manera de bajar el intervalo de llamadas para que sea por ejemplo una vez cada 5 minutos?

**Comment by ldotlopez** [comment]
Hola @pgalinanes 

Intentar bajar el intervalo de actualización es un buen ejercicio de lectura para comprender como funciona el código pero es una **MALA** idea llevarlo a cabo. Hay un 99% de posibilidades de que i-de bloquee tu usuario: https://github.com/ldotlopez/ha-ideenergy/blob/main/FAQ.md#q-why-accumulated-or-instant-consumption-sensors-are-only-updated-once-at-hour-can-be-this-interval-shorter

**Comment by pgalinanes** [comment]
Hola, muchas gracias por la aclaración. Ya veo que es algo de i-de y no de la integración. Dejo cerrado el hilo. Gracias de nuevo por vuestro trabajo
