### ISSUE TITLE
Upgraded to 2.0.0 and activated historical sensors - now data is gone - any chance to get it back?

### ISSUE THREAD

**Issue by hartmood** [ldotlopez/ha-ideenergy#48]
I upgraded to 2.0.0 and, for whatever reason, had in mind that the deactivated historical sensors were under investigation to be activated. Unfortunately, I did not read the manual indicating not to activate historical sensors. 

Can I get the data back, or shall I use my nightly backup?

**Comment by ldotlopez** [comment]
Hi,

Which data is gone?

**Comment by hartmood** [comment]
Any data from the last 6 months.

**Comment by ldotlopez** [comment]
Ok, but..

Data was the accumulated consumption? Some from historical sensors?
(pre-2.0 already have historical data)
All of them?

Which version do you come from?

Some entities were renamed:
- check if energy panel is using the current ones
- from developer tools check if any of our sensors has data over the last
week.

Can you provide some logs from the upgrade? Can you provide some of the
current logs?

If not I can recommend you to:
- enable debug log for custom_components.ideeneegy, ideenergy and
homeassistant_historical_sensor
- revert to the last working version of the integration
- restart HA
- restore your latest back.

Then we can check logs.

**Comment by hartmood** [comment]
```
- check if energy panel is using the current ones
- from developer tools check if any of our sensors has data over the last
week.
```
Data is now coming in and is reflected in the energy panel. But any data before the upgrade/activation of the sensors is gone.

```
Can you provide some logs from the upgrade? Can you provide some of the
current logs?

```
Maybe, but I don't know how


```
- enable debug log for custom_components.ideeneegy, ideenergy and
homeassistant_historical_sensor
- revert to the last working version of the integration
- restart HA
- restore your latest backup.

Then we can check logs
```
I will revert to last night's backup and then do the upgrade again. I am more than sure it was the activation of the three hidden historical sensors that caused the troubles.

**Comment by hartmood** [comment]
2.0.0 now works well in my installation. It must have been the historical sensors that crashed the database. Reading the fucking manual would have saved my ass.
