### ISSUE TITLE
Not working again

### ISSUE THREAD

**Issue by sirdir1972** [ldotlopez/ha-ideenergy#49]
I un- and reinstalled the old version and then finally it was back working. 
Then I saw there's an actualization to 2.0 
Did that enthusiastically and at first it worked, but after a few hours the updates stopped. Now I'm without new data for about 2 days again. 
I uninstalled the new version completely, restarted hass, installed it again, but that doesn't change anything. 
Where can I find information for debugging?

**Comment by ldotlopez** [comment]
Hi @sirdir1972 

Please check #50

**Comment by ldotlopez** [comment]
Closing by stale
