### ISSUE TITLE
agregar captcha, para loggin

### ISSUE THREAD

**Issue by Martins-Work** [ldotlopez/ha-ideenergy#51]
**Loggin con captcha.**

La web de i-DE muestra captha para logarme, por favor podrías agregar la funcionalidad y así poder usar el addon  

P.D. Gran trabajo, Gracias.

**Comment by ldotlopez** [comment]
Hola @Martins-Work 

La integración utiliza una autenticación distinta a la de la web. Acabo de comprobarlo con una instalación limpia y funciona correctamente.

Intenta comprobar si hay algún fallo con tu usuario mediante la herramienta de línea de comandos: github.com/ldotlopez/ideenergy

Saludos.
