### ISSUE TITLE
No tengo acceso a los datos?

### ISSUE THREAD

**Issue by danielccm** [ldotlopez/ha-ideenergy#56]
Desde hace unos días veo que no tengo acceso a los datos incluso reiniciando, y de hecho ahora he quitado la integración y ahora no me deja entrar.

He cambiado la contraseña en la web de i-de y nada...

Por la web sí puedo ver todo, pero en la integración nada de nada...

Me dice algo de la autenticación

**Comment by Letalwings** [comment]
A mi me ocurre lo mismo desde hace unos días.

Os pongo una imagen del error que me da. Desde la pagina de I-de puedo entrar y consultar los datos sin ningún problema.

![image](https://github.com/ldotlopez/ha-ideenergy/assets/104193198/e1e32895-1913-4251-a8f0-b9bea5446b5d)

Estos son los datos de como tengo actualmente HomeAssistant por si pudiera servir.

![image](https://github.com/ldotlopez/ha-ideenergy/assets/104193198/bb3e9267-541a-4da4-a9be-99c8ba262622)

**Comment by ldotlopez** [comment]
Hay un issue+PR pendiente en el módulo base `ideenergy` relacionado con el login: https://github.com/ldotlopez/ideenergy/pull/7

A ver si puedo sacar un rato esta tarde, yo también estoy afectado por el bug.

**Comment by ldotlopez** [comment]
Acabo de publicar una versión que debería solucionar el error

@danielccm @Letalwings si podéis probadla y comentarme si es así

**Comment by JanHACS** [comment]
Hola @ldotlopez , me pasaba lo mismo y acabo de descargarme la 2.0.4 y parece que ha solucionado al menos en parte los errores. Ahora de los 5 sensores que tengo, funcionan dos consumo instantáneo y acumulado, los otros 3 que son históricos los marca como desconocidos, aunque desconozco si es porque aún no ha pasado tiempo suficiente para que la integración las lea.

Un saludo y mil gracias ;-)

**Comment by danielccm** [comment]
> Acabo de publicar una versión que debería solucionar el error
> 
> @danielccm @Letalwings si podéis probadla y comentarme si es así

Eres un genio, gracias!

**Comment by ldotlopez** [comment]
> Eres un genio, gracias!

Agradecimientos a @luca-angemi que [actualizó](https://github.com/ldotlopez/ideenergy/pull/7) el client de i-de

**Comment by luca-angemi** [comment]
Hasta el próximo cambio! 
Deberíamos pedir una api oficial. 
Vergonzoso es que en 2023 una empresa tan grande no nos deje acceder a nuestros mismos datos.
